# Generated by Django 2.0.3 on 2018-04-29 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
