# Generated by Django 2.0.3 on 2018-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
