# Generated by Django 2.0.3 on 2018-05-01 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_competition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='submissions',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
