# Generated by Django 2.0.3 on 2018-05-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_description',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='submissions',
        ),
    ]
