# Generated by Django 2.0.3 on 2018-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20180430_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_score', models.IntegerField(default=0)),
            ],
        ),
    ]
