# Generated by Django 2.0.3 on 2018-05-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='competition',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
