# Generated by Django 2.0.3 on 2018-05-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20180501_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='deadline',
            field=models.DateField(),
        ),
    ]
