# Generated by Django 2.0.3 on 2018-05-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20180501_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='deadline',
        ),
    ]
