# Generated by Django 2.0.4 on 2018-04-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='pub_date',
        ),
    ]
